### ISSUE TITLE
Doc template not using the entire screen

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/ansys-sphinx-theme#325]
### Description of the modifications

The template does not scale with the screen resolution. This is impacting the rendering. I got complains already from users. Could we improve the space usage on screen ?

repo : https://github.com/ansys-internal/pyansys-edb

![image](https://github.com/ansys/ansys-sphinx-theme/assets/74993647/9442ddd8-400a-44ab-b14a-2759b206d288)

![image](https://github.com/ansys/ansys-sphinx-theme/assets/74993647/7804c492-1632-4e41-b590-1fe01e8cb9a3)

**Comment by ansbmartin** [comment]
I use the following [CSS](https://sphinxdocs.ansys.com/version/stable/user_guide/css.html#ref-user-guide-css) for this:
```css
.bd-main .bd-content .bd-article-container {
   max-width: unset;
}
.bd-page-width {
   max-width: unset;
}
table {
   width: 100%;
}
.bd-sidebar-primary {
   width: 15%;
}
```
